Document: authy-open-vpn
Title: Debian authy-open-vpn Manual
Author: <insert document author here>
Abstract: This manual describes what authy-open-vpn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/authy-open-vpn/authy-open-vpn.sgml.gz

Format: postscript
Files: /usr/share/doc/authy-open-vpn/authy-open-vpn.ps.gz

Format: text
Files: /usr/share/doc/authy-open-vpn/authy-open-vpn.text.gz

Format: HTML
Index: /usr/share/doc/authy-open-vpn/html/index.html
Files: /usr/share/doc/authy-open-vpn/html/*.html
