#!/bin/bash
#This command need to be called like ./postinstall DESTDIR=/usr/lib/authy
function check_root {
    if [[ "$(whoami)" != "root" ]]
    then
        echo "Please run this command as root."
        exit -1
    fi
}

function add_configuration {
    local conf_file=$1
    local string_to_add=$2
    echo "" >> $conf_file
    echo "# This line was added by the authy-openvpn installer" >> $conf_file
    echo "$string_to_add" >> $conf_file
}

function add_authy {
    local server_conf=$1
    local plugin=$2
    local key=$3
    local pam=$4

    sed -ie '/authy-openvpn/d' "$server_conf"
    add_configuration "$server_conf" "plugin $plugin https://api.authy.com/protected/json $key $pam"
}

function add_pam {
    local server_conf=$1
    local plugin=$2
    local pam_string=$3
    add_configuration "$server_conf" "plugin $plugin \"$pam_string\""
}

function prephase {
    echo -n "Do you want us to edit server.conf for you? (y/n): "
    read helpp
    if [ $helpp != 'y' ] ; then
        return 0
    fi

    local serverconf="/etc/openvpn/server.conf"
    if [ ! -f $serverconf ] ; then
      echo -n "Enter path to your openvpn configuration: "
      read serverconf
    fi

    if [ ! -f "$serverconf" ] ; then
        echo "Config file not found. Make sure you enter the absolute path."
        return 1
    fi

    echo -n "Authy API KEY: "
    read authy_key

    echo -n "Are you using OpenVPN with PAM? (y/n): "
    read helpp

    if [ $helpp != 'y' ] ; then
        add_authy $serverconf $AUTHYSO $authy_key "nopam"
    else
        add_authy $serverconf $AUTHYSO $authy_key "pam"

        local pam_string="login login USERNAME password PASSWORD"
        echo -n "The default pam is $pam_string . Is this OK? (y/n): "
        read helpp

        if [ $helpp == 'n' ]; then
            echo -n "Please enter your PAM string:"
            read pam_string
        fi
        add_pam $serverconf $PAMSO "$pam_string"
    fi

    echo ""
    echo "All done. Now start adding users using 'sudo authy-vpn-add-user'"
}

DESTDIR=/usr/lib/authy
AUTHYSO=$DESTDIR/authy-openvpn.so
PAMSO=$DESTDIR/pam.so

check_root
prephase
